# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170925_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
