# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_businessfeaturemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypeaccessmodel',
            name='userType',
            field=models.CharField(default='', max_length=15),
        ),
    ]
