# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170918_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userID',
            new_name='username',
        ),
    ]
