# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171016_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEditableFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.TextField()),
            ],
        ),
    ]
