# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171016_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessfeaturemodel',
            name='optionalMapSearchInput',
            field=models.CharField(default='---', max_length=1000),
        ),
    ]
