# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171016_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(default='Please provide your feedback here.', max_length=200)),
            ],
        ),
    ]
