# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admineditablefeatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admineditablefeatures',
            name='featureName',
        ),
        migrations.AddField(
            model_name='admineditablefeatures',
            name='featureDisplayName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admineditablefeatures',
            name='featureModelName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
