# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170919_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='lastName',
        ),
    ]
