# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170919_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='userID',
            new_name='username',
        ),
    ]
