# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20171007_1337'),
        ('accounts', '0006_featurelocationmodel_usertypeaccessmodel'),
    ]

    operations = [
    ]
